name: 'Azure App Configuration Pull'
description: 'Pull information from Azure App Configuration'
author: 'David Gardiner'
inputs:
  resourceGroup:
    required: true
    description: 'Resource Group that contains App Configuration resource'
  appConfigurationName:
    required: true
    description: 'Name of App Configuration resource'
  keyFilter:
    required: false
    description: 'Key filter'

runs:
  using: 'node12'
  main: 'dist/index.js'
